### ISSUE TITLE
Update for Terraria 1.4?

### ISSUE THREAD

**Issue by Renkyz** [Pryaxis/Vanillafier#2]
Hello, sorry if this is the wrong place to ask but I couldn't find anywhere more appropriate.
Will the Vanillafier plugin be updated for TShock 4.4.0 / Terraria 1.4? I really loved using this plugin on my 1.3 server with TShock and would like to continue using it, but when I tried to "Vanillafy" my new server, I got the following log:

[05/24/20 04:43:43] [Server API] Warning: Plugin "TShock" has had an unhandled exception thrown by one of its ServerCommand handlers: 
System.MissingFieldException: Field not found: 'TShockAPI.TShock.Users'.
   at Vanillafier.Vanillafier.Confirm(Object obj)
   at TShockAPI.Commands.HandleCommand(TSPlayer player, String text)
   at TShockAPI.TShock.ServerHooks_OnCommand(CommandEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in C:\Users\X\Documents\GitHub\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HandlerCollection.cs:line 109

If any further information is needed, please let me know.

**Comment by hakusaro** [comment]
You could vanillify the old server and upgrade, for the record.

**Comment by Renkyz** [comment]
Thanks for your reply hakusaro. We are using new characters and all have different IP addresses as well by now. So I'm not sure what difference that will make (we don't use SSC by the way). Which files should I be copying over from my old 1.3 server folder? I still have all that older stuff saved I think. I was too worried about copying files over in case they were incompatible with the new version of TShock as I understood several big changes had happened, so I pretty much set up our 1.4 server from scratch. Would you be able to advise me on which files are safe to vopy over to my current 1.4 server directory from the old 1.3 directory?

**Comment by QuiCM** [comment]
Updated :)
